var wordlist = [
'wonder woman',
'spider-man',
'batman',
'superman',
'wolverine',
'iron man',
'captain america',
'the hulk',
'black panther',
'the flash',
'Cyborg',
'deadpool',
'thor',
'jean grey',
'storm',
'daredevil',
'green lantern',
'batgirl',
'professor x',
'cat woman',
'blue beetle',
'black widow',
'supergirl',
'the thing',
'green arrow',
'doctor strange',
'captain marvel',
'silver surfer',
'luke cage',
'aquaman',
'nick fury',
'hellboy',
'human torch',
'rogue',
'falcon',
'nightcrawler',
'ant-man',
'nightwing',
'jessica jones',
'kitty pryde',
'Mr. Fantastic',
'blade',
'beast',
'punisher',
'cyclops',
'invisible woman',
'shazam',
'Azrael',
'hawkeye',
'martian manhunter'
];

var guessableLetters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i',
'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'];
