var wordlist = [
'Mexican wolf',
'red wolf',
"Stephen's kangaroo rat",
'Morro Bay kangaroo rat',
'giant kangaroo rat',
'kangaroo rat',
'Steller sea lion',
'Hawaiian hoary bat',
'Ocelot',
'lesser long-nosed bat',
'Mexican long-nosed bat',
'Amargosa vole',
'Mexican Hualapai vole',
'black-footed ferret',
'gray bat',
'Indiana bat',
'riparian woodrat',
'Cedros Island mule deer',
'rice rat',
'California bighorn sheep',
'Pacific pocket mouse',
'Key Largo cotton mouse',
'Gulf Coast jaguarundi',
'Sinaloan jaguarundi',
'woodland caribou',
'salt marsh harvest mouse',
'Delmarva Peninsula fox squirrel',
'Buena Vista Lake ornate shrew',
'Mount Graham red squirrel',
'West Indian manatee',
'island fox',
'grizzly bear',
'San Joaquin kit fox',
'Vancouver Island marmot',
'Florida panther',
'yellow-shouldered blackbird',
'whooping crane',
'California condor',
"Kirtland's warbler",
'ivory-billed woodpecker',
'St. Croix ground lizard',
'Culebra Island giant anole',
'loggerhead sea turtle',
'green sea turtle',
'spotted turtle',
'bog turtle',
'American crocodile',
"Morelet's crocodile",
'New Mexican ridge-nosed rattlesnake',
'Mona ground iguana',
'leatherback sea turtle',
'Central American river turtle',
'eastern indigo snake',
'hawksbill sea turtle',
'blunt-nosed leopard lizard',
'wood turtle',
'desert tortoise',
'yellow-blotched map turtle',
'Bolson tortoise',
'gopher tortoise',
'ringed map turtle',
'Gila monster',
"Kemp's ridley sea turtle",
'olive ridley sea turtle',
'alligator snapping turtle',
'Alameda whipsnake',
'sand skink',
'Alabama red-belly turtle',
'San Esteban Island chuckwalla',
'Monito gecko',
'flattened musk turtle',
'aquatic box turtle',
'giant garter snake',
'San Francisco garter snake',
'Coachella Valley fringe-toed lizard',
"Morelet's tree frog",
'California tiger salamander',
'Houston toad',
'Barton Springs salamander',
'Shenandoah salamander',
'mountain yellow-legged frog',
'Sierra Nevada Mountain yellow-legged frog',
'Texas blind salamander',
"Lange's metalmark butterfly",
'Uncompahgre fritillary butterfly',
"Hungerford's crawling water beetle",
'Salt Creek tiger beetle',
'Ohlone tiger beetle',
'El Segundo blue butterfly',
"Smith's blue butterfly",
'Quino checkerspot butterfly',
"Boisduval's blue butterfly",
'Karner blue butterfly',
'spruce-fir moss spider',
"Mitchell's satyr butterfly",
'American burying beetle',
'Laguna Mountains skipper',
'Callippe silverspot butterfly',
'Kretschmarr Cave mold beetle',
'Bee Creek cave harvestman',
'Zayante band-winged grasshopper',
'Hawaiian yellow-faced bee',
'shortnose sturgeon',
'Gulf sturgeon',
'Ozark cavefish',
'Modoc sucker',
'Santa Ana sucker',
'Warner sucker',
'great white shark',
'shortnose sucker',
'cui-ui',
'June sucker',
'White River springfish',
'Hiko White River springfish',
'Railroad Valley springfish',
'diamond darter',
'blue shiner',
'beautiful shiner',
'Leon Springs pupfish',
'Devils Hole pupfish',
'Comanche Springs pupfish',
'desert pupfish',
'Owens pupfish',
'Lost River sucker',
'Devils River minnow',
'desert dace',
'slender chub',
'slackwater darter',
'watercress darter',
'Okaloosa darter',
'boulder darter',
'tidewater goby',
'Big Bend gambusia',
'Clear Creek gambusia',
'Pecos gambusia',
'Mohave tui chub',
'Borax Lake chub',
'humpback chub',
'Sonara chub',
'bonytail chub',
'Gila chub',
'Chihuahua chub',
'Yaqui chub',
'Virgin River chub',
'Rio Grande silvery minnow',
'delta smelt',
'Yaqui catfish',
'White River spinedace',
'Little Colorado spinedace',
'spikedace',
'moapa dace',
'Cahaba shiner',
'Cape Fear shiner',
'yellowfin madtom',
'pygmy madtom',
'Scioto madtom',
'Apache trout',
'Lahontan cutthroat trout',
'Paiute cutthroat trout',
'greenback cutthroat trout',
'Gila trout',
'chum salmon',
'Oregon chub',
'amber darter',
'goldline darter',
'Conasauga logperch',
'leopard darter',
'Roanoke logperch',
'snail darter',
'blackside dace',
'woundfin',
'Gila toppminnow',
'smalltooth sawfish',
'Colorado pikeminnow',
'bull trout',
'pallid sturgeon',
'Alabama sturgeon',
'Alabama cavefish',
'loach minnow',
'razorback sucker',
'black abalone',
'white abalone',
'Nashville crayfish',
"O'ahu tree snails"
]

var guessableLetters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i',
'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'];
