var wordlist = ['Apple',
'red mung bean',
'Bakeable custard',
'Baked potato',
'Banana',
'Purple Sweet Potato',
'Blueberry cheesecake',
'Brown sugar syrup',
'Cafe au lait',
'Cantaloupe',
'Cappuccino',
'Caramel macchiato McFlurry',
'Cherry',
'Chestnut',
'Chocobanana',
'Cinnamon cookie',
'Citrus golden blend',
'Corn',
'Creme brulee',
'Double cookie',
'Edamame',
'European cheese',
'Exotic Tokyo',
'Fruit parfait',
'Ginger ale',
'Golden citrus',
'Green bean',
'Hojicha',
'Hokkaido cheese and chocolate',
'Hokkaido Melon with Mascarpone Cheese',
'Hokkaido roasted corn',
'Hot Japanese chili',
'roasted soy flour',
'Kobe pudding',
'black tea',
'double chocolate ganache',
'Lemon cheesecake',
'Maple',
'Matcha green tea',
'Miso soup',
'Muscat of Alexandria',
'Okinawa sweet potato',
'Passion fruit',
'Pear',
'lemon-lime',
'Raspberry passionfruit',
'Red potato',
'hotcakes and maple syrup',
'Rock salt',
'Royal Milk Tea',
'Sake',
'cherry blossom',
'cherry blossom matcha latte',
'Salt and caramel',
'flat lemon',
'Shinshu apple',
'Soy flour',
'Soy sauce',
'Strawberry',
'Strawberry cheesecake',
'Sweet pudding',
'Triple berry swirl',
'Vegetable juice',
'Wasabi',
'Watermelon',
'Yokohama cheesecake',
'Yubari melon',
'Yuzu',
'rum raisin',
'grape',
'orange and cream',
'orange',
'white chocolate',
'pumpkin pudding',
'brandy and orange',
'fruit parfait',
'apricot seed',
'white peach',
'red bean',
'french bretange milk',
'potato and sesame seed',
'pumpkin',
'double berry',
'red bean paste',
'mango',
'sweet bean paste',
'apple vinegar',
'pineapple',
'kiwi',
'bitter chocolate',
'jasmine tea',
'frozen dark chocolate',
'white and yellow peach'];


var guessableLetters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i',
'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'];
