var wordlist = ['Apple',
'Adzuki',
'Bakeable custard',
'Baked potato',
'Banana',
'Beni imo',
'Blueberry cheesecake',
'Brown sugar syrup',
'Cafe au lait',
'Cantaloupe',
'Cappuccino',
'Caramel macchiato McFlurry',
'Cherry',
'Chestnut',
'Chocobanana',
'Cinnamon cookie',
'Citrus golden blend',
'Corn',
'Creme brulee',
'Double cookie',
'Edamame',
'European cheese',
'Exotic Tokyo',
'Fruit parfait',
'Ginger ale',
'Golden citrus',
'Green bean',
'Hojicha',
'Hokkaido cheese and chocolate',
'Hokkaido Melon with Mascarpone Cheese',
'Hokkaido roasted corn',
'Hot Japanese chili',
'Kinako',
'Kobe pudding',
'Koucha',
'Kuchidoke Kakao',
'Lemon cheesecake',
'Maple',
'Matcha',
'Miso soup',
'Muscat of Alexandria',
'Okinawa sweet potato',
'Passion fruit',
'Pear',
'Ramune',
'Raspberry passionfruit',
'Red potato',
'Rilakkuma hotcake',
'Rock salt',
'Royal Milk Tea',
'Sake',
'Sakura',
'Sakura matcha latte',
'Salt and caramel',
'Shikuwasa',
'Shinshu apple',
'Soy flour',
'Soy sauce',
'Strawberry',
'Strawberry cheesecake',
'Sweet pudding',
'Triple berry swirl',
'Vegetable juice',
'Wasabi',
'Watermelon',
'Yokohama cheesecake',
'Yubari melon',
'Yuzu']
